robot:
  # Publish all joint states --------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: base-0_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: 0-1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: 1-2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: 2-4_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: 4-5_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: 5-6_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
